openapi: "3.0.3"

info:
  title: "Shop Review API"
  version: "1.0.0"
servers:
  - url: "http://localhost:{port}"
    description: "Local development"
    variables:
      port:
        enum: ["3000", "3001"]
        default: "3000"
  - url: "http://stg.api.com"
    description: "stg"
  - url: "http://api.api.com"
    description: "prd"

paths: {}
